from __future__ import annotations

import functools
from typing import List, Dict, Set

from dataclasses import dataclass

from Options import Toggle, OptionSet

from ..game import Game
from ..game_objective_template import GameObjectiveTemplate

from ..enums import KeymastersKeepGamePlatforms


# Option Dataclass
@dataclass
class TearsOfTheKingdomOptions:
    include_time_consuming_tasks: IncludeTimeConsumingTasks
    include_unreasonable_tasks: IncludeUnreasonableTasks


# Main Class
class TearsOfTheKingdomGame(Game):
    name = "The Legend of Zelda: Tears of the Kingdom"
    platform = KeymastersKeepGamePlatforms.SW

    platforms_other = [
        KeymastersKeepGamePlatforms.SW2
    ]

    is_adult_only_or_unrated = False

    options_cls = TearsOfTheKingdomOptions

    # Optional Game Constraints
    def optional_game_constraint_templates(self) -> List[GameObjectiveTemplate]:
        return [
            GameObjectiveTemplate(
                label="Do not use WEAPONS (if possible)",
                data={
                    "WEAPONS": (self.weapontypes, 1)
                },
            ),
        ]


    # Main Objectives
    def game_objective_templates(self) -> List[GameObjectiveTemplate]:
        return [
            GameObjectiveTemplate(
                label="Defeat BOSS",
                data={
                    "BOSS": (self.bosses, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Defeat OWBOSS",
                data={
                    "OWBOSS": (self.overworld_bosses, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Complete COUNT Shrines",
                data={
                    "COUNT" :(self.shrine_count, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Defeat COUNT ENEMY",
                data={
                    "COUNT": (self.enemy_count, 1),
                    "ENEMY": (self.enemies, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3
            ),
            GameObjectiveTemplate(
                label="Defeat COUNT HARDENEMY",
                data={
                    "COUNT": (self.hard_enemy_count, 1),
                    "HARDENEMY": (self.hard_enemies, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=2
            ),
            GameObjectiveTemplate(
                label="Activate COUNT Lightroots",
                data={
                    "COUNT": (self.lightroot_count, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Activate TOWER",
                data={
                    "COUNT": (self.towers, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Find COUNT Korok seeds",
                data={
                    "Count": (self.korok_count, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Obtain ARMOR",
                data={
                    "ARMOR": (self.armor, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Dye GEARTYPE COLOR",
                data={
                    "GEARTYPE": (self.gear_type, 1),
                    "COLOR": (self.color, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Obtain COUNT ITEM(s)",
                data={
                    "COUNT": (self.itemcount, 1),
                    "ITEM": (self.items, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Complete COUNT Side Quests",
                data={
                    "COUNT": (self.sidecount, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=2,
            ),
            GameObjectiveTemplate(
                label="Cook FOOD",
                data={
                    "FOOD": (self.food, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Complete COUNT Side Adventures",
                data={
                    "COUNT": (self.sidecount, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Obtain SAGE's Vow",
                data={
                    "SAGE": (self.sages, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Create something using DEVICE",
                data={
                    "DEVICE": (self.zonaidevices, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Ride an ANIMAL",
                data={
                    "ANIMAL": (self.rideable, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Take a selfie with BOSS using the camera rune",
                data={
                    "BOSS": (self.bosses, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Take a selfie with BOSS using the camera rune",
                data={
                    "BOSS": (self.overworld_bosses, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Take a selfie with ITEM using the camera rune",
                data={
                    "ITEM": (self.items, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Take a selfie with ENEMY using the camera rune",
                data={
                    "ENEMY": (self.enemies, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Take a selfie with ENEMY using the camera rune",
                data={
                    "ENEMY": (self.hard_enemies, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Take a selfie with EQUIPMENT using the camera rune",
                data={
                    "EQUIPMENT": (self.weapons, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Take a selfie with ANIMAL using the camera rune",
                data={
                    "ANIMAL": (self.animals, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Feed ANIMAL",
                data={
                    "ANIMAL": (self.feedable, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
            ]

    # "Template Include Hard Stuff" Option Property
    @property
    def include_time_consuming_tasks(self) -> bool:
        return bool(self.archipelago_options.include_time_consuming_tasks.value)

    @property
    def include_unreasonable_tasks(self) -> bool:
        return bool(self.archipelago_options.include_unreasonable_tasks.value)
    # Datasets

    @staticmethod
    def enemies() -> List[str]:
        return [
            "Chuchu",
            "Fire Chuchu",
            "Ice Chuchu",
            "Electric Chuchu",
            "Bokoblin",
            "Blue Bokoblin",
            "Black Bokoblin",
            "Stalkoblin",
            "Boss Bokoblin",
            "Blue Boss Bokoblin",
            "Black Boss Bokoblin",
            "Soldier Construct I",
            "Soldier Construct II",
            "Soldier Construct III",
            "Captain Construct I",
            "Captain Construct II",
            "Gibdo",
            "Moth Gibdo",
            "Horriblin",
            "Blue Horriblin",
            "Black Horriblin",
            "Keese",
            "Electric Keese",
            "Fire Keese",
            "Ice Keese",
            "Lizalfos",
            "Blue Lizalfos",
            "Black Lizalfos",
            "Stalizalfos",
            "Moblin",
            "Blue Moblin",
            "Black Moblin",
            "Stalmoblin",
            "Water Octorok",
            "Forest Octorok",
            "Rock Octorock",
            "Yiga Footsoldier",
            "Stone Pebblit",
            "Frost Pebblit",
            "Igneo Pebblit",
            "Like Like",
            "Fire Like",
            "Ice Like",
            "Shock Like",
            "Rock Like",
            "Little Frost",
            "Evermean",
            "Aerocuda",
        ]

    @staticmethod
    def enemy_count() -> range:
        return range(5, 15)
    
    @staticmethod
    def hard_enemies() -> List[str]:
        return [
            "Silver Bokoblin",
            "Silver Boss Bokoblin",
            "Soldier Construct IV",
            "Captain Construct III",
            "Captain Construct IV",
            "Silver Horriblin",
            "Keese Swarm",
            "Silver Lizalfos",
            "Lynel",
            "Blue-maned Lynel",
            "White-maned Lynel",
            "Silver Lynel",
            "Silver Moblin",
            "Fire Wizzrobe",
            "Meteo Wizzrobe",
            "Frost Wizzrobe",
            "Blizzrobe",
            "Electric Wizzrobe",
            "Thunder Wizzrobe",
            "Yiga Blademaster",
            "Gloom Spawn",
        ]

    @staticmethod
    def hard_enemy_count() -> range:
        return range(1, 3)
    
    @staticmethod
    def bosses() -> List[str]:
        return [
            "Colgera",
            "Marbled Gohma",
            "Mucktorok",
            "Queen Gibdo",
            "Master Kohga",
        ]

    @staticmethod
    def overworld_bosses() -> List[str]:
        return [
            "Stone Talus",
            "Stone Talus (Luminous)",
            "Stone Talus (Rare)",
            "Battle Talus",
            "Igneo Talus",
            "Frost Talus",
            "Hinox",
            "Blue Hinox",
            "Black Hinox",
            "Stalnox",
            "Molduga",
            "Flame Gleeok",
            "Frost Gleeok",
            "Thunder Gleeok",
            "King Gleeok",
            "Flux Construct I",
            "Flux Construct II",
            "Flux Construct III",
            "Frox",
            "Obsidian Frox",
            "Blue-White Frox",
            "Phantom Ganon",
        ]
    
    @staticmethod
    def shrine_count() -> range:
        return range(2, 5)

    @staticmethod
    def lightroot_count() -> range:
        return range(3, 8)

    @staticmethod
    def towers() -> List[str]:
        return [
            "Lookout Landing Skyview Tower",
            "Hyrule Field Skyview Tower",
            "Londor's Brow Skyview Tower",
            "Upland Zorana Skyview Tower",
            "Sahasra Slope Skyview Tower",
            "Rospro Pass Skyview Tower",
            "Pikida Stonegrove Skyview Tower",
            "Thyphlo Ruins Skyview Tower",
            "Eldin Canyon Skyview Tower",
            "Ulri Mountains Skyview Tower",
            "Mount Lanayru Skyview Tower",
            "Rabella Wetlands Skyview Tower",
            "Popla Foothills Skyview Tower",
            "Gerudo Canyon Skyview Tower",
            "Gerudo Highlands Skyview Tower",
        ]
    
    @staticmethod
    def weapontypes() -> List[str]:
        return [
            "One-Handed Swords",
            "Two-handed Swords",
            "Spears",
            "Bows",
            "Shields",
        ]
        
    @staticmethod
    def korok_count() -> range:
        return range(5, 25)
    
    @staticmethod
    def sages() -> list:
        return [
            "Tulin, Sage of Wind",
            "Yunobo, Sage of Fire",
            "Sidon, Sage of Water",
            "Riju, Sage of Lightning",
            "Mineru, Sage of Spirit",
        ]
    
    @functools.cached_property
    def armor_base(self) -> List[str]:
        return[
            "Archaic Tunic",
            "Archaic Legwear",
            "Archaic Warm Greaves",
            "Hylian Hood",
            "Hylian Tunic",
            "Hylian Trousers",
            "Soldier's Helm",
            "Soldier's Armor",
            "Soldier's Greaves",
            "Snowquill Headdress",
            "Snowquill Tunic",
            "Snowquill Trouswers",
            "Flamebreaker Helm",
            "Flamebreaker Armor",
            "Flamebreaker Boots",
            "Zora Helm",
            "Zora Armor",
            "Zora Greaves",
            "Desert Voe Headband",
            "Desert Voe Spaulder",
            "Desert Voe Trouswers",
            "Rubber Helm",
            "Rubber Armor",
            "Rubber Tights",
            "Stealth Mask",
            "Stealth Chest Guard",
            "Stealth Tights",
            "Climber's Bandana",
            "Climbing Gear",
            "Climbing Boots",
            "Barbarian Helm",
            "Barbarian Armor",
            "Barbarian Leg Wraps",
            "Radiant Mask",
            "Radiant Shirt",
            "Radiant Tights",
            "Royal Guard Cap",
            "Royal Guard Uniform",
            "Royal Guard Boots",
            "Glide Mask",
            "Glide Shirt",
            "Glide Tights",
            "Miner's Mask",
            "Miner's Top",
            "Miner's Trousers",
            "Ember Headdress",
            "Ember Shirt",
            "Ember Trousers",
            "Frostbite Headdress",
            "Frostbite Shirt",
            "Frostbite Trousers",
            "Yiga Mask",
            "Yiga Armor",
            "Yiga Tights",
            "Vah Medoh Devine Helm",
            "Vah Rudania Divine Helm",
            "Vah Ruta Divine Helm",
            "Vah Naboris Divine Helm",
            "Zonaite Helm",
            "Zonaite Waistguard",
            "Zonaite Shin Guards",
            "Diamond Circlet",
            "Ruby Circlet",
            "Sapphire Circlet",
            "Topaz Earrings",
            "Opal Earrings",
            "Amber Earrings",
            "Well-Worn Hair Band",
            "Lightning Helm",
            "Sand Boots",
            "Snow Boots",
            "Bokoblin Mask",
            "Moblin Mask",
            "Champion's Leathers",
            "Island Lobster Shirt",
            "Ravio's Hood",
            "Zant's Helmet",
            "Midna's Helmet",
            "Majora's Mask",
            "Korok Mask",
            "Tingle's Hood",
            "Tingle's Shirt",
            "Tingle's Tights",
            "Phantom Helmet",
            "Phantom Armor",
            "Phantom Greaves",
            "Evil Spirit Mask",
            "Evil Spirit Armor",
            "Evil Spirit Greaves",
            "Sheik's Mask",
            "Fierce Deity Mask",
            "Fierce Deity Armor",
            "Fierce Deity Boots",
            "Mask of Awakening",
            "Tunic of Awakening",
            "Trousers of Awakening",
            "Cap of the Wild",
            "Tunic of the Wild",
            "Trousers of the Wild",
            "Cap of the Hero",
            "Tunic of the Hero",
            "Trousers of the Hero",
            "Cap of Time",
            "Tunic of Time",
            "Trousers of Time",
            "Cap of the Wind",
            "Tunic of the Wind",
            "Trousers of the Wind",
            "Cap of Twilight",
            "Tunic of Twilight",
            "Trousers of Twilight",
            "Cap of the Sky",
            "Tunic of the Sky",
            "Trousers of the Sky",
        ]
    
    @functools.cached_property
    def time_consuming_armor(self) -> List[str]:
        return [
            "Mystic Headpiece",
            "Mystic Robe",
            "Mystic Trousers",
			"Froggy Hood",
            "Froggy Sleeve",
            "Froggy Leggings",
			"Hood of the Depths",
            "Tunic of the Depths",
            "Gaiters of the Depths",
			"Charged Headdress",
            "Charged Shirt",
            "Charged Trousers",
			"Cece's Hat",
			"Horriblin Mask",
            "Lizalfos Mask",
            "Lynel Mask",
			"Tunic of Memories",
			"Dark Hood",
            "Dark Tunic",
            "Dark Trousers",
        ]
    
    @functools.cached_property
    def unreasonable_armor(self) -> List[str]:
        return [
            "Ancient Hero's Aspect",
        ]
    
    def armor(self) -> List[str]:
        armor: List[str] = self.armor_base[:]

        if self.include_time_consuming_tasks:
            armor.extend(self.time_consuming_armor[:])

        if self.include_unreasonable_tasks:
            armor.extend(self.unreasonable_armor[:])
        return sorted(armor)
    
    @staticmethod
    def gear_type() -> List[str]:
        return [
            "Head Piece",
            "Body Piece",
            "Leg Piece",
        ]
    
    @staticmethod
    def color() -> List[str]:
        return [
            "Blue",
            "Red",
            "Yellow",
            "White",
            "Black",
            "Purple",
            "Green",
            "Light Blue",
            "Navy",
            "Orange",
            "Peach",
            "Crimson",
            "Light Yellow",
            "Brown",
            "Gray",
        ]
    
    @staticmethod
    def items() -> List[str]:
        return [
            "Acorn",
            "Aerocuda Eyeball",
            "Aerocuda Wing",
            "Amber",
            "Ancient Arowana",
            "Ancient Blade",
            "Apple",
            "Armoranth",
            "Armored Carp",
            "Armored Porgy",
            "Big Hearty Radish",
            "Big Hearty Truffle",
            "Bird Egg",
            "Black Bokoblin Horn",
            "Black Boss Bokoblin Horn",
            "Black Hinox Horn",
            "Black Lizalfos Horn",
            "Black Lizalfos Tail",
            "Black Moblin Horn",
            "Bladed Rhino Beetle",
            "Blue Bokoblin Horn",
            "Blue Boss Bokoblin Horn",
            "Blue Hinox Horn",
            "Blue Horriblin Horn",
            "Blue Lizalfos Horn",
            "Blue Lizalfos Tail",
            "Blue Moblin Horn",
            "Blue Nightshade",
            "Blue-Maned Lynel Mace Horn",
            "Blue-Maned Lynel Saber Horn",
            "Blue-White Frox Fang",
            "Bokoblin Fang",
            "Bokoblin Guts",
            "Bokoblin Horn",
            "Bomb Flower",
            "Boss Bokoblin Fang",
            "Boss Bokoblin Guts",
            "Boss Bokoblin Horn",
            "Brightbloom Seed",
            "Brightcap",
            "Bright-Eyed Crab",
            "Cane Sugar",
            "Captain Construct I Horn",
            "Captain Construct II Horn",
            "Captain Construct III Horn",
            "Captain Construct IV Horn",
            "Chickaloo Tree Nut",
            "Chillfin Trout",
            "Chillshroom",
            "Chuchu Jelly",
            "Cold Darner",
            "Cool Safflina",
            "Courser Bee Honey",
            "Dark Clump",
            "Dazzle Fruit",
            "Deep Firefly",
            "Diamond",
            "Dinraal's Claw",
            "Dinraal's Horn",
            "Dinraal's Scale",
            "Electric Darner",
            "Electric Keese Eyeball",
            "Electric Keese Wing",
            "Electric Lizalfos Horn",
            "Electric Lizalfos Tail",
            "Electric Safflina",
            "Endura Carrot",
            "Endurra Shroom",
            "Energetic Rhino Beetle",
            "Fairy",
            "Farosh's Claw",
            "Farosh's Horn",
            "Farosh's Scale",
            "Fire Fruit",
            "Fire Keese Eyeball",
            "Fire Keese Wing",
            "Fire Like Stone",
            "Fire-Breath Lizalfos Horn",
            "Fire-Breath Lizalfos Tail",
            "Fireproof Lizard",
            "Fleet Lotus Seeds",
            "Flint",
            "Fortified Pumpkin",
            "Fresh Milk",
            "Frox Fang",
            "Frox Fingernail"
            "Frox Guts",
            "Giant Brightbloom Seed",
            "Gibdo Bone",
            "Gibdo Guts",
            "Gibdo Wing",
            "Gleeok Flame Horn",
            "Gleeok Frost Horn",
            "Gleeok Guts",
            "Gleeok Thunder Horn",
            "Gleeok Wing",
            "Glowing Cave Fish",
            "Goat Butter",
            "Golden Apple",
            "Goron Spice",
            "Hateno Cheese",
            "Hearty Bass",
            "Hearty Lizard",
            "Hearty Radish",
            "Hearty Salmon",
            "Hearty Truffle",
            "Hightail Lizard",
            "Hinox Guts",
            "Hinox Toenail",
            "Hinox Tooth",
            "Horriblin Claw",
            "Horriblin Guts",
            "Horriblin Horn",
            "Hot-Footed Frog",
            "Hydromelon",
            "Hylian Rice",
            "Hylian Shroom",
            "Hylian Tomato",
            "Hyrule Bass",
            "Hyrule Herb",
            "Ice Fruit",
            "Ice Keese Eyeball",
            "Ice Keese Wing",
            "Ice Like Stone",
            "Ice-Breath Lizalfos Horn",
            "Ice-Breath Lizalfos Tail",
            "Ironshell Crab",
            "Ironshroom",
            "Keese Eyeball",
            "Keese Wing",
            "Korok Frond",
            "Like Like Stone",
            "Light Dragon's Horn",
            "Light Dragon's Scale",
            "Light Dragon's Talon",
            "Lizalfos Horn",
            "Lizalfos Talon",
            "Lizalfos Tail",
            "Lynel Guts",
            "Lynel Hoof",
            "Lynel Mace Horn",
            "Lynel Saber Horn",
            "Mighty Bananas",
            "Mighty Carp",
            "Mighty Porgy",
            "Mighty Thistle",
            "Moblin Fang",
            "Moblin Guts",
            "Moblin Horn",
            "Molduga Fin",
            "Molduga Guts",
            "Monster Extract",
            "Muddle Bud",
            "Naydra's Claw",
            "Naydra's Horn",
            "Naydra's Scale",
            "Obsidian Frox Fang",
            "Octo Balloon",
            "Octorok Eyeball",
            "Octorok Tentacle",
            "Oil Jar",
            "Opal",
            "Puffshroom",
            "Raw Bird Drumstick",
            "Raw Meat",
            "Razorclaw Crab",
            "Razorshroom",
            "Red Chuchu Jelly",
            "Restless Cricket",
            "Rock Salt",
            "Ruby",
            "Rugged Rhino Beetle",
            "Rushroom",
            "Sanke Carp",
            "Sapphire",
            "Shard of Dinraal's Fang",
            "Shard of Dinraal's Spike",
            "Shard of Farosh's Fang",
            "Shard of Farosh's Spike",
            "Shard of Light Dragon's Fang",
            "Shard of Light Dragon's Spike",
            "Shard of Naydra's Fang",
            "Shard of Naydra's Spike",
            "Shock Fruit",
            "Shock Like Stone",
            "Silent Princess",
            "Silent Shroom",
            "Silver Boss Bokoblin Horn",
            "Silver Horriblin Horn",
            "Silver Lizalfos Tail",
            "Silver Lynel Mace Horn",
            "Silver Lynel Saber Horn",
            "Silver Moblin Horn",
            "Sizzlefin Trout",
            "Skyshroom",
            "Smotherwing Butterfly",
            "Sneaky River Snail",
            "Soldier Construct Horn",
            "Soldier Construct II Horn",
            "Soldier Construct III Horn",
            "Soldier Construct IV Horn",
            "Spicy Pepper",
            "Splash Fruit",
            "Stalnox Horn",
            "Stambulb",
            "Stamella Shroom",
            "Staminoka Bass",
            "Star Fragment",
            "Stealthfin Trout",
            "Sticky Lizard",
            "Summerwing Butterfly",
            "Sunset Firefly",
            "Sundelion",
            "Sunshroom",
            "Sun Pumpkin",
            "Swift Carrot",
            "Swift Violet",
            "Tabantha Wheat",
            "Thunderwing Butterfly",
            "Tireless Frog",
            "Topaz",
            "Voltfin Trout",
            "Voltfruit",
            "Warm Darner",
            "warm Safflina",
            "White Chuchu Jelly",
            "White-Maned Lynel Saber Horn",
            "Wildberry",
            "Winterwing Butterfly",
            "Wood",
            "Yellow Chuchu Jelly",
            "Zapshroom",
            "Zonai Charge",
            "Zonaite",
        ]
    
    @staticmethod
    def itemcount() -> range:
        return range (1, 10)
    
    @staticmethod
    def sidecount() -> range:
        return range (2,5)
    
    @staticmethod
    def food() -> List[str]:
        return [
            "Mushroom Skewer",
			"Meat and Mushroom Skewer",
			"Fish and Mushroom Skewer",
			"Meat Skewer",
			"Fish Skewer",
			"Seafood Skewer",
			"Copious Meat Skewers",
			"Copious Seafood Skewers",
			"Steamed Fruit",
			"Steamed Tomatoes",
			"Steamed Mushrooms",
			"Steamed Meat",
			"Steamed Fish",
			"Sautéed Peppers",
			"Sautéed Nuts",
			"Fried Wild Greens",
			"Copious Fried Wild Greens",
			"Cooked Stambulb",
			"Buttered Stambulb",
			"Copious Mushroom Skewers",
			"Spiced Meat Skewer",
			"Prime Spiced Meat Skewer",
			"Gourmet Spiced Meat Skewer",
			"Crab Stir-Fry",
			"Meat and Seafood Fry",
			"Prime Meat and Seafood Fry",
			"Gourmet Meat and Seafood Fry",
			"Salt-Grilled Greens",
			"Salt-Grilled Mushrooms",
			"Salt-Grilled Meat",
			"Salt-Grilled Prime Meat",
			"Salt-Grilled Gourmet Meat",
			"Salt-Grilled Fish",
			"Salt-Grilled Crab",
			"Herb Sauté",
			"Fragrant Mushroom Sauté",
			"Pepper Steak",
			"Pepper Seafood",
			"Fragrant Seafood Stew",
			"Deep-Fried Drumstick",
			"Deep-Fried Thigh",
			"Deep-Fried Bird Roast",
			"Seafood Meunière",
			"Porgy Meunière",
			"Salmon Meunière",
			"Fruit and Mushroom Mix",
			"Simmered Fruit",
			"Copious Simmered Fruit",
			"Simmered Tomato",
			"Fruity Tomato Stew",
			"Tomato Mushroom Stew",
			"Tomato Seafood Soup",
			"Cream of Vegetable Soup",
			"Veggie Cream Soup",
			"Cream of Mushroom Soup",
			"Creamy Meat Soup",
			"Creamy Seafood Soup",
			"Snail Chowder",
			"Creamy Heart Soup",
			"Glazed Veggies",
			"Glazed Mushrooms",
			"Glazed Meat",
			"Glazed Seafood",
			"Curry Rice",
			"Vegetable Curry",
			"Meat Curry",
			"Prime Meat Curry",
			"Gourmet Meat Curry",
			"Poultry Curry",
			"Prime Poultry Curry",
			"Gourmet Poultry Curry",
			"Seafood Curry",
			"Cheesy Curry",
			"Carrot Stew",
			"Pumpkin Stew",
			"Meat Stew",
			"Prime Meat Stew",
			"Gourmet Meat Stew",
			"Meat-Stuffed Pumpkin",
			"Vegetable Risotto",
			"Mushroom Risotto",
			"Salmon Risotto",
			"Crab Risotto",
			"Cheesy Risotto",
			"Poultry Pilaf",
			"Prime Poultry Pilaf",
			"Gourmet Poultry Pilaf",
			"Seafood Paella",
			"Curry Pilaf",
			"Fried Egg and Rice",
			"Crunchy Fried Rice",
			"Seafood Fried Rice",
			"Crab Omelet with Rice",
			"Meat and Rice Bowl",
			"Prime Meat and Rice Bowl",
			"Gourmet Meat and Rice Bowl",
			"Cheesy Meat Bowl",
			"Prime Cheesy Meat Bowl",
			"Gourmet Cheesy Meat Bowl",
			"Veggie Rice Balls",
			"Mushroom Rice Balls",
			"Meaty Rice Balls",
			"Seafood Rice Balls",
			"Veggie Porridge",
			"Wheat Bread",
			"Melty Cheesy Bread",
			"Hylian Tomato Pizza",
			"Meat Pie",
			"Fish Pie",
			"Cheesy Tomato",
			"Cheesy Baked Fish",
			"Omelet",
			"Vegetable Omelet",
			"Mushroom Omelet",
			"Cheesy Omelet",
			"Hot Buttered Apple",
			"Honeyed Fruits",
			"Honeyed Apple",
			"Honey Candy",
			"Fried Bananas",
			"Egg Pudding",
			"Plain Crepe",
			"Wildberry Crepe",
			"Honey Crepe",
			"Nutcake",
			"Fruitcake",
			"Carrot Cake",
			"Pumpkin Pie",
			"Cheesecake",
			"Fruit Pie",
			"Apple Pie",
			"Egg Tart",
			"Milk",
			"Noble Pursuit",
			"Monster Stew",
			"Monster Soup",
			"Monster Curry",
			"Monster Rice Balls",
			"Monster Cake",
			"Dark Stew",
			"Dark Soup",
			"Dark Curry",
			"Dark Rice Ball",
			"Dark Cake",
			"Dubious Food",
			"Rock-Hard Food",
			"Baked Apple",
			"Baked Golden Apple",
			"Charred Pepper",
			"Roasted Hylian Tomato",
			"Roasted Wildberry",
			"Roasted Voltfruit",
			"Roasted Hydromelon",
			"Baked Palm Fruit",
			"Roasted Mighty Bananas",
			"Roasted Lotus Seeds",
			"Roasted Mighty Thistle",
			"Roasted Armoranth",
			"Roasted Swift Carrot",
			"Roasted Endura Carrot",
			"Baked Fortified Pumpkin",
			"Baked Sun Pumpkin",
			"Roasted Radish",
			"Roasted Big Radish",
			"Toasty Skyshroom",
			"Toasty Hylian Shroom",
			"Toasty Stamella Shroom",
			"Toasty Rushroom",
			"Toasty Sunshroom",
			"Toasty Chillshroom",
			"Toasty Zapshroom",
			"Toasty Razorshroom",
			"Toasty Ironshroom",
			"Toasty Silent Shroom",
			"Toasty Brightcap",
			"Toasty Endura Shroom",
			"Toasted Hearty Truffle",
			"Toasted Big Hearty Truffle",
			"Seared Steak",
			"Seared Prime Steak",
			"Seared Gourmet Steak",
			"Roasted Bird Drumstick",
			"Roasted Bird Thigh",
			"Roasted Whole Bird",
			"Roasted Arowana",
			"Roasted Bass",
			"Roasted Trout",
			"Roasted Carp",
			"Roasted Porgy",
			"Roasted Cave Fish",
			"Roasted Hearty Bass",
			"Roasted Hearty Salmon",
			"Blackened Crab",
			"Sneaky River Escargot",
			"Roasted Tree Nut",
			"Roasted Acorn",
			"Campfire Egg",
			"Hard-Boiled Egg",
			"Icy Meat",
			"Icy Prime Meat",
			"Icy Gourmet Meat",
			"Frozen Bird Drumstick",
			"Frozen Bird Thigh",
			"Frozen Whole Bird",
			"Frozen Arowana",
			"Frozen Bass",
			"Frozen Trout",
			"Frozen Carp",
			"Frozen Porgy",
			"Frozen Cave Fish",
			"Frozen Hearty Bass",
			"Frozen Hearty Salmon",
			"Frozen Crab",
			"Frozen River Snail",
			"Energizing Elixir",
			"Hasty Elixir",
			"Spicy Elixir",
			"Chilly Elixir",
			"Electro Elixir",
			"Fireproof Elixir",
			"Mighty Elixir",
			"Tough Elixir",
			"Sneaky Elixir",
			"Sticky Elixir",
			"Bright Elixir",
			"Enduring Elixir",
			"Hearty Elixir",
			"Fairy Tonic",
        ]
    
    @staticmethod
    def zonaidevices() -> List[str]:
        return [
            "Fan",
            "Wing",
            "Cart",
            "Balloon",
            "Rocket",
            "Time Bomb",
            "Portable Pot",
            "Flame Emitter",
            "Frost Emitter",
            "Shock Emitter",
            "Beam Emitter",
            "Hydrant",
            "Steering Stick",
            "Big Wheel",
            "Small Wheel",
            "Sled",
            "Battery",
            "Big Battery",
            "Spring",
            "Cannon",
            "Stabilizer",
            "Hover Stone",
            "Light",
            "Stake",
            "Mirror",
            "Homing Cart",
            "Construct Head",
        ]
    @staticmethod
    def rideable() -> List[str]:
        return [
            "Deer",
            "Bear",
            "Sand Seal",
            "Stalhorse",
            "Solid Coloured Horse",
            "Speckled Horse",
            "Lynel",
            "Giant White Stallion",
            "Giant Horse",
            "Royal White Horse",
            "Golden Horse",
        ]
    
    @staticmethod
    def weapons() -> List[str]:
        return [
            "Bokoblin Arm",
            "Boomerang",
            "Eightfold Blade",
            "Feathered Edge",
            "Forest Dweller's Sword",
            "Gerudo Scimitar",
            "Gloom Sword",
            "Gnarled Wooden Stick",
            "Knight's Broadsword",
            "Lizal Boomerang",
            "Lizalfos Arm",
            "Magic Rod",
            "Master Sword",
            "Mighty Zonaite Sword",
            "Royal Broadsword",
            "Royal Guard's Sword",
            "Rusty Broadsword",
            "Scimitar of the Seven",
            "Sea-breeze Boomerang",
            "Soldier's Broadsword",
            "Soup Ladle",
            "Strong Zonaite Sword",
            "Sturdy Wooden Stick",
            "Sword of the Hero",
            "Torch",
            "Traveler's Sword",
            "Tree Branch",
            "White Sword of the Sky",
            "Wooden Stick",
            "Zonaite Sword",
            "Zora Sword",
            "Biggoron's Sword",
            "Boat Oar",
            "Boulder Breaker",
            "Cobble Crusher",
            "Dusk Claymore",
            "Eightfold Longblade",
            "Farming Hoe",
            "Fierce Deity Sword",
            "Gerudo Claymore",
            "Giant Boomerang",
            "Gloom Club",
            "Gnarled Thick Stick",
            "Knight's Claymore",
            "Magic Scepter",
            "Mighty Zonaite Longsword",
            "Moblin Arm",
            "Royal Claymore",
            "Royal Guard's Claymore",
            "Rusty Claymore",
            "Soldier's Claymore",
            "Strong Zonaite Longsword",
            "Sturdy Thick Stick",
            "Thick Stick",
            "Traveler's Claymore",
            "Zonaite Longsword",
            "Zora Longsword",
            "Farmer's Pitchfork",
            "Feathered Spear",
            "Fishing Harpoon",
            "Forest Dweller's Spear",
            "Gerudo Spear",
            "Gloom Spear",
            "Gnarled Long Stick",
            "Knight's Halberd",
            "Lightscale Trident",
            "Long Stick",
            "Magic Staff",
            "Mighty Zonaite Spear",
            "Royal Guard's Spear",
            "Royal Halberd",
            "Rusty Halberd",
            "Soldier's Spear",
            "Strong Zonaite Spear",
            "Sturdy Long Stick",
            "Throwing Spear",
            "Traveler's Spear",
            "Wooden Mop",
            "Zonaite Spear",
            "Zora Spear",
            "Boko Bow",
            "Construct Bow",
            "Demon King's Bow",
            "Dragonbone Boko Bow",
            "Duplex Bow",
            "Dusk Bow",
            "Falcon Bow",
            "Forest Dweller's Bow",
            "Gerudo Bow",
            "Great Eagle Bow",
            "Knight's Bow",
            "Lizal Bow",
            "Lynel Bow",
            "Mighty Construct Bow",
            "Mighty Lynel Bow",
            "Old Wooden Bow",
            "Phrenic Bow",
            "Royal Bow",
            "Royal Guard's Bow",
            "Savage Lynel bow",
            "Soldier's Bow",
            "Spiked Boko Bow",
            "Steel Lizal Bow",
            "Strengthened Lizal Bow",
            "Strong Construct Bow",
            "Swallow Bow",
            "Traveler's Bow",
            "Wooden Bow",
            "Zonaite Bow",
            "Zora Bow",
            "Boko Shield",
            "Daybreaker",
            "Dragonbone Boko Shield",
            "Emblazoned Shield",
            "Fisherman's Shield",
            "Forest Dweller's Shield",
            "Gerudo Shield",
            "Hunter's Shield",
            "Hylian Shield",
            "Kite Shield",
            "Lizal Shield",
            "Lynel Shield",
            "Mighty Lynel Shield",
            "Old Wooden Shield",
            "Pot Lid",
            "Radiant Shield",
            "Reinforced Lizal Shield",
            "Royal Guard's Shield",
            "Royal Shield",
            "Rusty Shield",
            "Savage Lynel Shield",
            "Sea-Breeze Shield",
            "Shield of the Mind's Eye",
            "Soldier's Shield",
            "Steel Lizal Shield",
            "Strong Zonaite Shield",
            "Traveler's Shield",
            "Wooden Shield",
            "Zonaite Shield",
            "Zora Shield",
        ]
    
    @staticmethod
    def animals() -> List[str]:
        return [
            "Horse",
            "Giant Horse",
            "White Horse",
            "Giant White Stallion",
            "Golden Horse",
            "Stalhorse",
            "Donkey",
            "Sand Seal",
            "Patricia",
            "Bushy-Tailed Squirrel",
            "Woodland Boar",
            "Red-Tusked Boar",
            "Mountain Goat",
            "White Goat",
            "Mountain Buck",
            "Mountain Doe",
            "Water Buffalo",
            "Hateno Cow",
            "Highland Sheep",
            "Grassland Fox",
            "Snowcoat Fox",
            "Maraudo Wolf",
            "Wasteland Coyote",
            "Cold-Footed Wolf",
            "Tabantha Moose",
            "Dondon",
            "Honeyvore Bear",
            "Grizzlemaw Bear",
            "Hylian Retriever",
            "Blupee",
            "Bubbulfrog",
            "Common Sparrow",
            "Red Sparrow",
            "Blue Sparrow",
            "Rainbow Sparrow",
            "Sand Sparrow",
            "Golden Sparrow",
            "Wood Pigeon",
            "Rainbow Pigeon",
            "Hotfeather Pigeon",
            "White Pigeon",
            "Accented Pigeon",
            "Mountain Crow",
            "Bright-Chested Duck",
            "Blue-Winged Heron",
            "Pink Heron",
            "Islander Hawk",
            "Seagull",
            "Cloud Seagull",
            "Eldin Ostrich",
            "Forest Ostrich",
            "Cucco",
            "Hyrule Bass",
            "Hearty Bass",
            "Staminoka Bass",
            "Hearty Salmon",
            "Chillfin Trout",
            "Sizzlefin Trout",
            "Voltfin Trout",
            "Stealthfin Trout",
            "Mighty Carp",
            "Armored Carp",
            "Sanke Carp",
            "Ancient Arowana",
            "Glowing Cave Fish",
            "Mighty Porgy",
            "Armored Porgy",
            "Sneaky River Snail",
            "Razorclaw Crab",
            "Ironshell Crab",
            "Bright-Eyed Crab",
            "Fairy",
            "Winterwing Butterfly",
            "Summerwing Butterfly",
            "Thunderwing Butterfly",
            "Smotherwing Butterfly",
            "Cold Darner",
            "Warm Darner",
            "Electric Darner",
            "Restless Cricket",
            "Bladed Rhino Beetle",
            "Rugged Rhino Beetle",
            "Energetic Rhino Beetle",
            "Sunset Firefly",
            "Deep Firefly",
            "Hot-Footed Frog",
            "Tireless Frog",
            "Sticky Frog",
            "Hightail Lizard",
            "Hearty Lizard",
            "Fireproof Lizard",
            "Sticky Lizard",
        ]
    
    @staticmethod
    def feedable() -> List[str]:
        return [
            "Hylian Retriever",
            "Horse",
            "Dondon",
            "Sand Seal",
            "Wild Boar",
            "Wild Squirrel",
            "Yiga Clan Member",
        ]

# Archipelago Options

class IncludeTimeConsumingTasks(Toggle):
        """
    Indicates whether to include Time Consuming Tasks when generating Template objectives.
    """
        display_name = "Include Time Consuming Tasks"

class IncludeUnreasonableTasks(Toggle):
        """
    Indicates whether to include unreasonable tasks when generating Template objectives. Not a good idea for shorter asyncs.
    """
        
        display_name = "Include Unreasonable Tasks"
